Added cni add changes, its corresponding p4 artifacts
vishala-r/k8s-infra-offload pull request #5
Opened 2022-11-11 19:34 UTC by vishala-r

This program is tested with k8s framework for ping

Signed-off-by: Vishalakshi <vishalakshi.r@intel.com>

2022-11-14 14:39 UTC, dhruvpt requested changes

2022-11-14 14:39 UTC, dhruvpt commented on k8s_dp/k8s_dp.p4
> -    bit<48> dst_mac;
Why are we changing the indentation from 4 to 8 spaces?
Because of this, the whole file seems to have changed and it makes reviewing the logic changes difficult.
If we have to change the indentation, we should have that as separate commit.

2022-11-14 14:39 UTC, dhruvpt commented on k8s_dp/k8s_dp.p4
> +			        if (tx_balance_tcp.apply().hit) {
Are we mixing the services related changes in this CNI related changes?
Each commit should focus one change as a time otherwise, it gets very hard to track and isolate different features as and when they get submitted.

2022-11-15 23:30 UTC, venkateshpnv approved these changes

2022-11-15 23:33 UTC, venkateshpnv commented
The changes have been tested and below are the logs.
The arp proxy is successfully responding to the arp requests from the pods.

The changes are tested by manually adding the default route to the pods. These manual steps would not be required once the infra-agent default route add changes go in.

[root@mev03 k8s-infra-offload]# nsenter -t 388339 -n ping 10.244.0.7
PING 10.244.0.7 (10.244.0.7) 56(84) bytes of data.
64 bytes from 10.244.0.7: icmp_seq=1 ttl=64 time=0.272 ms
64 bytes from 10.244.0.7: icmp_seq=2 ttl=64 time=0.260 ms
64 bytes from 10.244.0.7: icmp_seq=3 ttl=64 time=0.276 ms
64 bytes from 10.244.0.7: icmp_seq=4 ttl=64 time=0.291 ms
64 bytes from 10.244.0.7: icmp_seq=5 ttl=64 time=0.313 ms
64 bytes from 10.244.0.7: icmp_seq=6 ttl=64 time=0.356 ms
64 bytes from 10.244.0.7: icmp_seq=7 ttl=64 time=0.272 ms
64 bytes from 10.244.0.7: icmp_seq=8 ttl=64 time=0.244 ms


[root@mev03 k8s-infra-offload]# nsenter -t 388339 -n ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
46: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether aa:4d:8f:6e:d8:e5 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.6/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a84d:8fff:fe6e:d8e5/64 scope link
       valid_lft forever preferred_lft forever


Gateway logs – arp proxy

time="2022-11-15T15:04:15-08:00" level=debug msg="Received new packet for IP 10.233.132.6" func=main.runARPProxy file="/home/vpetla/k8s-infra-offload/arp-proxy/cmd/main.go:66"
time="2022-11-15T15:04:15-08:00" level=debug msg="Received an ARP request" func=main.runARPProxy file="/home/vpetla/k8s-infra-offload/arp-proxy/cmd/main.go:73"
time="2022-11-15T15:04:15-08:00" level=debug msg="Request: who-has 10.233.132.6?  tell 10.244.0.5 (1e:b8:62:7f:b0:85)" func=main.runARPProxy file="/home/vpetla/k8s-infra-offload/arp-proxy/cmd/main.go:76"
time="2022-11-15T15:04:15-08:00" level=debug msg="  Reply: 10.233.132.6 is-at e6:a1:eb:02:ec:07" func=main.runARPProxy file="/home/vpetla/k8s-infra-offload/arp-proxy/cmd/main.go:79"
time="2022-11-15T15:04:50-08:00" level=debug msg="Received new packet for IP 10.233.132.6" func=main.runARPProxy file="/home/vpetla/k8s-infra-offload/arp-proxy/cmd/main.go:66"
time="2022-11-15T15:04:50-08:00" level=debug msg="Received an ARP request" func=main.runARPProxy file="/home/vpetla/k8s-infra-offload/arp-proxy/cmd/main.go:73"
time="2022-11-15T15:04:50-08:00" level=debug msg="Request: who-has 10.233.132.6?  tell 10.244.0.4 (42:95:da:e3:24:93)" func=main.runARPProxy file="/home/vpetla/k8s-infra-offload/arp-proxy/cmd/main.go:76"
time="2022-11-15T15:04:50-08:00" level=debug msg="  Reply: 10.233.132.6 is-at e6:a1:eb:02:ec:07" func=main.runARPProxy file="/home/vpetla/k8s-infra-offload/arp-proxy/cmd/main.go:79"


[root@mev03 k8s-infra-offload]# nsenter -t 388499 -n ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
47: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 2e:33:33:20:d6:47 brd ff:ff:ff:ff:ff:ff
    inet 10.244.0.7/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::2c33:33ff:fe20:d647/64 scope link
       valid_lft forever preferred_lft forever

2022-11-16 05:19 UTC, vishala-r commented on k8s_dp/k8s_dp.p4
> +			        if (tx_balance_tcp.apply().hit) {
no. adding service changes will not affect any functionality. since we are not programming any rule for service. 
this is inline with the discussion we had where we decided to check in the latest p4

2022-11-16 05:19 UTC, vishala-r commented on k8s_dp/k8s_dp.p4
> -    bit<48> dst_mac;
yes. will do.

2022-11-16 15:11 UTC, dhruvpt commented on k8s_dp/k8s_dp.p4
> +			        if (tx_balance_tcp.apply().hit) {
Ok, that was probably not the right decision. Ideally, we need to push only one logical change or one feature in a commit or PR. Because, in general, mixing multiple things in one commit leads to problems. For now, due to lack of time, we can go ahead with this but going forward, let's keep each feature on a separate branch of its own.

2022-11-16 19:16 UTC, merged